sudo: required
services:
    - docker

before_install:
    - docker build -t srikanth/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true srikanth/docker-react npm run test -- --coverage
